apiVersion: v1
kind: Service
metadata:
  name: ielts-planner
spec:
  type: NodePort
  selector:
    app: ielts-planner        # gom mọi pod có nhãn này
  ports:
    - port: 80                # cổng nội bộ cluster
      targetPort: 5000        # cổng app trong container
      nodePort: 30500         # cổng mở ra ngoài trên IP của lab-server